# Generated by Django 2.1 on 2021-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
